name: acme/migrate-db
title: Database Migration Tool
description: CLI tool for running database migrations with Atlas integration
type: cli-command
entry: cmd/main.go
templates:
  - templates/cmd/main.go.tmpl
  - templates/migration.go.tmpl
  - templates/README.md.tmpl
destination: internal/vpkg/acme/migrate-db
version: v0.1.0
license: MIT
author: ACME Corp
tags:
  - full-backend
  - eda
  - database
dependencies:
  - ariga.io/atlas/sql/migrate
  - github.com/spf13/cobra