name: vandor/redis-cache
title: Redis Cache
description: Simple Redis adapter using go-redis/v9 with Fx integration
type: fx-module
entry: redis.go
templates:
  - templates/redis.go.tmpl
  - templates/README.md.tmpl
destination: internal/vpkg/vandor/redis-cache
version: v0.1.0
license: MIT
author: Vandor Team
tags:
  - full-backend
  - eda
  - minimal
  - cache
dependencies:
  - github.com/redis/go-redis/v9
  - go.uber.org/fx